source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.3’
use_frameworks!

target 'LeituraDeBolso' do
  pod 'Alamofire', '~> 4.0’
  pod 'RealmSwift', '~> 2.0.0'
end

target 'LeituraDeBolsoTests' do
  pod 'Alamofire', '~> 4.0’
  pod 'RealmSwift', '~> 2.0.0'
end
